import type { Blog, Career } from './types';

export const fallbackCareers: Career[] = [
  {
    slug: 'frontend-developer',
    title: 'Frontend Developer',
    category: 'Software Engineering',
    description: 'Build responsive, accessible web interfaces with React, TypeScript, and modern design systems.',
    overview: 'Frontend developers translate product ideas into polished browser experiences. They work closely with designers, backend engineers, and product managers to create interfaces that are fast, accessible, and easy to use.',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    averageSalaryMin: 70000,
    averageSalaryMax: 125000,
    difficulty: 'beginner',
    demandScore: 92,
    requiredSkills: ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Accessibility'],
    responsibilities: ['Build reusable UI components.', 'Improve performance and accessibility.', 'Collaborate with designers and backend engineers.'],
    salaryInformation: 'Frontend salaries depend on framework depth, portfolio quality, and ability to ship maintainable user experiences.',
    careerGrowth: ['Junior Frontend Developer', 'Frontend Developer', 'Senior Frontend Developer', 'Frontend Architect'],
    tools: ['React', 'Next.js', 'Tailwind CSS', 'Figma'],
    learningPath: ['Master HTML, CSS, and JavaScript.', 'Build React projects.', 'Learn accessibility and performance.'],
    relatedCareerSlugs: ['full-stack-developer', 'ui-ux-designer'],
    isFeatured: true,
    status: 'published',
  },
  {
    slug: 'data-analyst',
    title: 'Data Analyst',
    category: 'Data & AI',
    description: 'Turn raw data into reports, dashboards, and business insights using SQL and visualization tools.',
    overview: 'Data analysts help teams make better decisions by cleaning, exploring, and explaining data. This path suits people who enjoy patterns, questions, and clear storytelling.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    averageSalaryMin: 65000,
    averageSalaryMax: 110000,
    difficulty: 'beginner',
    demandScore: 88,
    requiredSkills: ['SQL', 'Excel', 'Python', 'Tableau', 'Statistics'],
    responsibilities: ['Create dashboards.', 'Analyze trends.', 'Explain insights to stakeholders.'],
    salaryInformation: 'Data analyst compensation improves with SQL depth, domain expertise, and business communication skills.',
    careerGrowth: ['Junior Data Analyst', 'Data Analyst', 'Senior Data Analyst', 'Analytics Manager'],
    tools: ['SQL', 'Power BI', 'Tableau', 'Python'],
    learningPath: ['Learn spreadsheet analysis.', 'Practice SQL daily.', 'Build dashboard case studies.'],
    relatedCareerSlugs: ['data-scientist', 'business-intelligence-developer'],
    isFeatured: true,
    status: 'published',
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'Cybersecurity',
    description: 'Monitor threats, investigate alerts, and strengthen systems against security risks.',
    overview: 'Cybersecurity analysts protect organizations by detecting suspicious activity, responding to incidents, and improving security practices.',
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
    averageSalaryMin: 72000,
    averageSalaryMax: 130000,
    difficulty: 'intermediate',
    demandScore: 94,
    requiredSkills: ['Networking', 'Linux', 'SIEM', 'Incident Response', 'Risk Analysis'],
    responsibilities: ['Review security alerts.', 'Document incidents.', 'Recommend risk reductions.'],
    salaryInformation: 'Security salaries rise with incident response experience, cloud security knowledge, and certifications.',
    careerGrowth: ['SOC Analyst', 'Cybersecurity Analyst', 'Security Engineer', 'Security Architect'],
    tools: ['Splunk', 'Wireshark', 'Linux', 'Cloud IAM'],
    learningPath: ['Learn networking.', 'Practice Linux fundamentals.', 'Study common attack patterns.'],
    relatedCareerSlugs: ['security-engineer', 'cloud-security-specialist'],
    isFeatured: true,
    status: 'published',
  },
  {
    slug: 'ai-product-engineer',
    title: 'AI Product Engineer',
    category: 'Data & AI',
    description: 'Build AI-powered product features using full-stack engineering, prompt design, and evaluation.',
    overview: 'AI product engineers combine user empathy, software engineering, and AI workflow design to create practical features powered by language models.',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
    averageSalaryMin: 105000,
    averageSalaryMax: 180000,
    difficulty: 'advanced',
    demandScore: 96,
    requiredSkills: ['TypeScript', 'APIs', 'Prompt Engineering', 'Evaluation', 'Security'],
    responsibilities: ['Design AI workflows.', 'Evaluate outputs.', 'Ship safe AI features.'],
    salaryInformation: 'AI product engineering pays strongly when candidates can connect AI capability to reliable product value.',
    careerGrowth: ['Full-Stack Developer', 'AI Product Engineer', 'Senior AI Engineer', 'AI Product Lead'],
    tools: ['Next.js', 'Express', 'Gemini API', 'Zod'],
    learningPath: ['Build full-stack apps.', 'Learn prompt evaluation.', 'Add AI features safely.'],
    relatedCareerSlugs: ['machine-learning-engineer', 'full-stack-developer'],
    isFeatured: true,
    status: 'published',
  },
];

export const fallbackBlogs: Blog[] = [
  {
    slug: 'how-to-choose-your-first-tech-career',
    title: 'How to Choose Your First Tech Career',
    excerpt: 'A practical framework for comparing skills, interests, salary expectations, and learning timelines before choosing a path.',
    content: 'Choosing a technology career is easier when you compare daily work, learning curve, hiring demand, and your personal energy. Start with three paths, build one small project for each, and track which work feels sustainable.',
    coverImageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    category: 'Career Planning',
    tags: ['career', 'planning'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 5,
    status: 'published',
    publishedAt: '2026-06-01',
  },
  {
    slug: 'resume-summary-examples-for-tech-roles',
    title: 'Resume Summary Examples for Modern Tech Roles',
    excerpt: 'Learn how to write concise resume summaries that highlight strengths without exaggerating experience.',
    content: 'A strong summary connects your skills, evidence, and target role. Avoid inflated claims. Use concrete technologies, project outcomes, and the kind of role you are pursuing.',
    coverImageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',
    category: 'Resume',
    tags: ['resume', 'job search'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 4,
    status: 'published',
    publishedAt: '2026-06-03',
  },
  {
    slug: 'skills-that-make-junior-developers-stand-out',
    title: 'Skills That Make Junior Developers Stand Out',
    excerpt: 'Debugging, communication, and project ownership can matter as much as framework knowledge for early-career developers.',
    content: 'Junior developers stand out when they can explain how they solved problems, tested their work, and improved after feedback. A small finished project with clear notes is often stronger than a large unfinished clone.',
    coverImageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    category: 'Skills',
    tags: ['developer', 'skills'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 4,
    status: 'published',
    publishedAt: '2026-06-05',
  },
  {
    slug: 'data-careers-compared-analyst-scientist-engineer',
    title: 'Data Careers Compared: Analyst, Scientist, and Engineer',
    excerpt: 'Compare three popular data paths by daily work, required tools, and the type of problems each role solves.',
    content: 'Data analysts focus on reporting and business questions. Data scientists build models and experiments. Data engineers create the pipelines and platforms that make reliable analysis possible.',
    coverImageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    category: 'Career Planning',
    tags: ['data', 'analytics'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 5,
    status: 'published',
    publishedAt: '2026-06-07',
  },
  {
    slug: 'cybersecurity-career-roadmap',
    title: 'A Practical Cybersecurity Career Roadmap',
    excerpt: 'Start with networking and operating systems, then grow into monitoring, incident response, and cloud security.',
    content: 'Cybersecurity careers reward fundamentals. Learn how systems communicate, how identities are managed, and how attackers commonly move through environments before specializing too early.',
    coverImageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
    category: 'Security',
    tags: ['security', 'roadmap'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 6,
    status: 'published',
    publishedAt: '2026-06-09',
  },
  {
    slug: 'ai-skills-for-every-technology-career',
    title: 'AI Skills Every Technology Professional Should Learn',
    excerpt: 'Prompting, evaluation, automation, and responsible AI use are becoming practical baseline skills across tech roles.',
    content: 'AI skills are most useful when paired with domain knowledge. Learn how to write clear instructions, check outputs, protect sensitive data, and measure whether an AI workflow actually improves the work.',
    coverImageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',
    category: 'AI',
    tags: ['ai', 'productivity'],
    authorName: 'CareerCoach Ai Editorial Team',
    readTimeMinutes: 4,
    status: 'published',
    publishedAt: '2026-06-11',
  },
];

export const testimonials = [
  { name: 'Maya Chen', role: 'Frontend Developer', quote: 'CareerCoach Ai helped me compare paths and explain my project work with much more confidence.' },
  { name: 'Jordan Ellis', role: 'Data Analyst', quote: 'The recommendations made my learning plan feel focused instead of overwhelming.' },
  { name: 'Priya Raman', role: 'Cybersecurity Analyst', quote: 'I used the resume summary tool to turn scattered experience into a clear professional story.' },
];

export const faqs = [
  { question: 'Is CareerCoach Ai only for beginners?', answer: 'No. The platform supports beginners, career switchers, and experienced professionals comparing next-step technology roles.' },
  { question: 'Does the AI write fake experience?', answer: 'No. The AI prompts are designed to avoid inventing employers, degrees, dates, or certifications.' },
  { question: 'Can I save multiple career paths?', answer: 'Yes. Signed-in users can save careers, add notes, and track progress from the dashboard.' },
  { question: 'Do I need a resume to start?', answer: 'No. You can explore careers first, then use your skills and goals to generate summaries and recommendations.' },
];
